use vinabook
CREATE TABLE DANHMUC(
	MaDM INT identity(01,1) NOT NULL PRIMARY KEY,
	TenDM NVARCHAR(200)
)

CREATE TABLE PHATHANHSACH(
	MAPHATHANH INT identity NOT NULL PRIMARY KEY,
	TENNPT NVARCHAR(200),
)
CREATE TABLE SACH(
	MASACH UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	TENSACH NVARCHAR(200),
	GIATIEN FLOAT,
	SLTONKHO INT,
	NGAYNHAPHANG DATE,
	NHAXUATBAN NVARCHAR(200),
	MAPHATHANH INT NOT NULL, 
	MADM int,
	CONSTRAINT FK_MAPHATHANH1 FOREIGN KEY(MAPHATHANH) REFERENCES PHATHANHSACH(MAPHATHANH),
	CONSTRAINT FK_MADANHMUC1 foreign key(MADM) references DANHMUC(MADM)
)
go

create table KHACHHANG(
	MAKH INT identity(01,1) NOT NULL PRIMARY KEY,
	TENKH NVARCHAR(200),
	SDT varchar(220),
	DIACHI NVARCHAR(MAX),
	Email NVARCHAR(MAX),
	Account NVARCHAR(MAX),
	Pass NVARCHAR(MAX),
)

create table TACGIA(
	MATG INT identity NOT NULL PRIMARY KEY,
	TENTG NVARCHAR(MAX),
	NGAYSINHTG date
)


CREATE TABLE NHANVIEN(
	MANV INT identity(1000,1) NOT NULL PRIMARY KEY,
	TENNV NVARCHAR(MAX),
	GIOITINH NVARCHAR(MAX),
	VITRI NVARCHAR(MAX),
	NGAYSINH NVARCHAR(MAX),
	NGAYTHUE NVARCHAR(MAX),
	DIACHINV NVARCHAR(MAX),
	SDT varchar,
	LUONG int
)
create table shipper(
	MASHIPPER INT identity(01,1) NOT NULL PRIMARY KEY,
	TENCTY NVARCHAR(MAX),
	SDTCTY BIGINT
)
CREATE TABLE BINHLUAN(
	MABL INT identity(01,1) NOT NULL PRIMARY KEY,
	MAKH INT NOT NULL,
	MASACH UNIQUEIDENTIFIER DEFAULT NEWID(),
	DANHGIA varchar(max),
	CONSTRAINT FK_MAKH1 FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_MASACH1 FOREIGN KEY(MASACH) REFERENCES SACH(MASACH),
)

CREATE TABLE DONHANG(
	MADH INT identity(01,1) NOT NULL PRIMARY KEY,
	TENSHIPPER NVARCHAR(MAX),
	SDTSHIPPER varchar(20),
	DIACHIGH NVARCHAR(MAX),
	MAKH INT NOT NULL,
	MANV INT NOT NULL,
	MASHIPPER INT NOT NULL,
	CONSTRAINT FK_MAKH2 FOREIGN KEY(MAKH) REFERENCES KHACHHANG(MAKH),
	CONSTRAINT FK_MANV1 FOREIGN KEY(MANV) REFERENCES NHANVIEN(MANV),
	CONSTRAINT FK_MASHIPPER1 FOREIGN KEY(MASHIPPER) REFERENCES SHIPPER(MASHIPPER),
	PTDATHANG NVARCHAR(MAX),
	NGAYDATHANG DATE,
	NGAYDUDINHSHIP DATE
)



CREATE TABLE DONHANG_CHITIET(
	MADH INT NOT NULL,
	MASACH UNIQUEIDENTIFIER DEFAULT NEWID(),
	CONSTRAINT PR_MADH_MASACH PRIMARY KEY(MADH, MASACH),
	CONSTRAINT FK_MADH FOREIGN KEY(MADH) REFERENCES DONHANG(MADH),
	CONSTRAINT FK_MASACH FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE SANGTAC(
	MATG INT NOT NULL,
	MASACH UNIQUEIDENTIFIER DEFAULT NEWID(),
	NAMST DATE,
	CONSTRAINT PR_MATG_MASACH PRIMARY KEY(MATG, MASACH),
	CONSTRAINT FK_MATG FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
	CONSTRAINT FK_MASACH2 FOREIGN KEY(MASACH) REFERENCES SACH(MASACH)
)

CREATE TABLE HOPTAC(
	MATG INT NOT NULL,
	MAPHATHANH INT NOT NULL,
	NGAYKIHOPDONG DATE,
	NGAYHETHAN DATE,
	CONSTRAINT PR_MATG_MAPHATHANH PRIMARY KEY(MATG, MAPHATHANH),
	CONSTRAINT FK_MATG3 FOREIGN KEY(MATG) REFERENCES TACGIA(MATG),
	CONSTRAINT FK_MAPHATHANH FOREIGN KEY(MAPHATHANH) REFERENCES PHATHANHSACH(MAPHATHANH)
)
			
INSERT INTO [dbo].[DANHMUC] (TenDM)
VALUES
( N'Sách Ngoại Văn'),
( N'Sách Kinh Tế'),
( N'Sách Văn Học Trong Nước'),
( N'Sách Văn Học Nước Ngoài'),
(N'Sách Thưởng Thức - Đời Sống'),
( N'Sách Thiếu Nhi'),
(N'Sách Phát Triển Bản Thân'),
( N'Sách Tin Học - Ngoại Ngữ'),
(N'Sách Chuyên Ngành'),
( N'Sách Giáo Khoá - Giáo Trình'),
( N'Tạp Chí - Văn Phòng Phẩm')

INSERT INTO [dbo].[PHATHANHSACH] (TENNPT)
VALUES
( N'NHÃ NAM'),
(N'ALPHA BOOKS'),
(N'ĐÔNG TÂY'),
( N'NXB VĂN HÓA VĂN NGHỆ'),
( N'NHÀ SÁCH HOA SEN'),
( N'NXB TRẺ'),
(N'ĐÔNG A DC'),
(N'CỔ NGUYỆT'),
( N'COMICOLA'),
( N'CTCP TINH VĂN'),
( N'CTCP SÁCH AN TIÊM'),
(N'CORGI CHILDRENS'),
( N'CÔNG TY TRUYỀN ĐĂNG'),
( N'CTCP QUANG MINH'),
( N'CTY HẢI GIANG'),
( N'1980BOOKS'),
( N'BẮC HÀ'),
(N'BẢO KHÔI'),
( N'BIZBOOKS'),
( N'BLUEWAY'),
( N'CADASA'),
(N'CẨM PHONG BOOKS'),
( N'CAO VĂN QUANG'),
( N'BRISTISH BOOKS'),
( N'BẢO NHI'),
( N'BESTBOOK'),
( N'AZ VIỆT NAM'),
( N'CTTNHH PHẦN MỀM TIN HỌC ANH NGỌC'),
( N'CỬA HÀNG THỊNH PHONG'),
(N'CTY SÁCH LẠC HỒNG');
